spring:
  active:
    profiles: dev
    
server:
  port: 8080
    
eureka:
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
    nonSecurePort: ${server.port}
    securePort: ${server.port}
    securePortEnabled: true
  client:
    enabled: true
    healthcheck.enabled: true
    securePortEnabled: true

management:
  endpoint.prometheus.enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
      base-path: "/"
