#server:
#  ssl:
#    key-store: classpath:ssl/keystore/flairbi-keystore.p12
#    key-alias: flairbi
#    key-store-password: changeit
#    key-store-type: PKCS12
#    key-password: changeit
#    trust-store: classpath:ssl/keystore/flairbi-truststore.p12
#    trust-store-type: PKCS12
#    trust-store-password: changeit
#    enabled: true
#    enabled-protocols: [TLSv1.1, TLSv1.2]


# ===================================================================
# GRPC
# ===================================================================
grpc:
  tls:
    enabled: true
    root-certificate: ${GRPC_ROOT_CA:ca.crt}