# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #        url: jdbc:postgresql://localhost:5432/flairbissl=true&sslfactory=com.flair.bi.ssl.FlairBIPgSqlSSLSocketFactory&sslfactoryarg=src/main/resources/config/ssl/ssl-prod.properties
    url: jdbc:postgresql://192.168.99.100:5432/flairbi?ssl=false
    username: postgres
    password: admin
  jpa:
    database-platform: com.flair.bi.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  mail:
    host: 192.168.99.100
    port: 25
    username:
    password:
  thymeleaf:
    cache: true

liquibase:
  contexts: prod,
  drop-first: true

server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  ssl:
        key-store: classpath:ssl/keystore/flairbi-keystore.p12
        key-alias: flairbi
        key-store-password: changeit
        key-store-type: PKCS12
        key-password: changeit
        trust-store: classpath:ssl/keystore/flairbi-truststore.p12
        trust-store-type: PKCS12
        trust-store-password: changeit
        enabled: false
        enabled-protocols: [TLSv1.1, TLSv1.2]

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    rememberMe:
      # security key (this key should be unique for your application, and kept secret)
      key: 81703cb4a1c3099ecc374a94c5c4efe0717e078b
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: flairbi@192.168.99.100
    baseUrl: http://localhost:80
  metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
    jmx.enabled: true
    graphite:
      enabled: false
      host: 192.168.99.100
      port: 2003
      prefix: flairbi
    prometheus:
      enabled: false
      endpoint: /prometheusMetrics
    logs: # Reports Dropwizard metrics in the logs
      enabled: false
      reportFrequency: 60 # in seconds
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queueSize: 512

  # ===================================================================
  # Ldap connection properties
  # ===================================================================
  ldapsettings:
    url: ldap://localhost:10389
    base: dc=hawk,dc=com
    userDn: uid=admin,ou=system
    password: secret

# ===================================================================
# Application specific properties
# ===================================================================
application:
  fbi-engine:
    authentication:
      pki:
        key-store: classpath:ssl/keystore/flairbi-keystore.p12
        key-store-password: changeit
        key-password: changeit
        trust-store: classpath:ssl/keystore/flairbi-truststore.p12
        trust-store-password: changeit
        enabled: false
      basic-authentication:
        enabled: false
        username: admin
        password: admin
couchdb:
  password: password
  username: admin
  url: http://192.168.99.100:5984
  test-connection-at-startup: false
  database-name: flairbi-view
  ssl-factory: com.flair.bi.ssl.FlairBIPgSqlSSLSocketFactory
  ssl-factory-arg: src/main/resources/config/ssl/ssl-dev.properties
  enable-s-s-l: true


# ===================================================================
# vizualization-service-mode
# ===================================================================

vizualization-service-mode: grpc

# ===================================================================
# Images location
# note : please append the slash('/') at the end of folder as below
# for example : images then /
# ===================================================================

image-location: var/images/
image-max-size-mb: 10

#websocket message size
MAX_TEXT_MESSAGE_SIZE : 2048000

# ===================================================================
# Application scheduler configuration
# ===================================================================    

flair-ai-api:
  username: admin
  password: admin
  auth-url : http://devsupport-vizcentric.com:9100/api-token-auth/
  schedule-report-url : http://devsupport-vizcentric.com:9100/flairServiceApi/
  mail_body : This is a test email to check api functionality
  slack_API_Token : xoxp-338558815156-339648235094-401148640099-d844d7552f5b0081546729d997e92f52
  channel_id : C9ZK2705U
  stride_API_Token : uEkHqU5s2tsF6H13zK3p
  stride_cloud_id : 13f8bfc9-8748-4008-8b11-71f22aa84126
  stride_conversation_id : ff15d817-3ab3-417d-8ba6-2490b330a35f
  
# ===================================================================
# files location
# note : please append the slash('/') at the end of folder as below
# for example : files then /
# ===================================================================

storage-data-files: storage/data/files/

data-file-max-size-mb: 10